### ISSUE TITLE
Not able to rackup with blockchain-lite 1.3

### ISSUE THREAD

**Issue by judavi** [openblockchains/centralbank#1]
Hi @geraldb I keep playing with the project and I notice that now the project is not working with the blockchain-lite 1.3

![captura de pantalla 2017-12-20 a la s 2 03 41 p m](https://user-images.githubusercontent.com/1766933/34210657-8fc40b48-e58e-11e7-81a8-7a918f408ae7.png)

after I change the Gemfile to use 1.2 comebacks to work again

**Comment by geraldb** [comment]
Thanks for trying. Sorry I see just added the merkletree gem this morning. Please add the gem 'merkletree' to the Gemfile and retry.   Or just try `gem install merkletree` for a "global" gem install.  Let me know if that works.

**Comment by judavi** [comment]
No luck 
![captura de pantalla 2017-12-20 a la s 3 08 58 p m](https://user-images.githubusercontent.com/1766933/34213624-adf0e880-e597-11e7-9541-2f859feecbb3.png)

**Comment by geraldb** [comment]
thanks for the update. Will try to update the centralbank later today (or tommorow). Sure if you're interested in keeping the Dockerfile update-to-date (e.g. blockchain-lite 1.3 is out!) more than welcome (if you're interested I can send you an invite for the org (via github) so you can edit /change the Dockerfile "inline" without pull request. Cheers.

**Comment by judavi** [comment]
sure! sounds good! thanks!

**Comment by geraldb** [comment]
Welcome.  Note: You will get an invitation (by email from GitHub) to join the Open Blockchains org as a member. If you accept, you can update the centralbank & tulipmania repos in your browser  - no longer any need for a pull request - and you will show up in the people page too (if you set your preference to public - default is private; change the setting in the [github org people page](https://github.com/orgs/openblockchains/people)).

**Comment by kolopeda** [comment]
@geraldb , thank you for your work.

**Comment by geraldb** [comment]
FYI: I've added the missing command line called centralbank and updated the library dependencies. Please retry.Thanks. Happy holiday / merry christmas. Cheers.

**Comment by judavi** [comment]
@geraldb I'm still facing issues with blockchain-lite-1.3.1

![captura de pantalla 2017-12-25 a la s 4 52 27 p m](https://user-images.githubusercontent.com/1766933/34341658-1050db52-e994-11e7-8549-12b3a5a22144.png)


Even after add merkle tree on the Gemfile

![captura de pantalla 2017-12-25 a la s 4 53 13 p m](https://user-images.githubusercontent.com/1766933/34341661-20aa5f82-e994-11e7-898b-57bb4e367997.png)


btw happy holidays for you too! :)

**Comment by geraldb** [comment]
Thanks for retrying. Weird. The error is a missing require 'merkletree' in the centralbank.rb script - please double check that you have the centralbank code / repo updated e.g.  use $ git pull or something.  Check that you have this line / require -> <https://github.com/openblockchains/centralbank/blob/master/lib/centralbank.rb#L15> in your (local) code.

**Comment by judavi** [comment]
Totally my bad 😸  I was playing in another branch (not in master)
tested and is working correctly with the latest version! Thanks!
